"""add unique constraint ranked_entries

Revision ID: 1ae43da752b0
Revises: bcaa51f4fc9b
Create Date: 2026-05-20 23:43:46.798504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae43da752b0'
down_revision: Union[str, Sequence[str], None] = 'bcaa51f4fc9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_ranked_puuid_queue', 'ranked_entries', ['puuid', 'queue_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ranked_puuid_queue', 'ranked_entries', type_='unique')
    # ### end Alembic commands ###
