"""test after change structure

Revision ID: 3980fb83271c
Revises: dfcc829741f8
Create Date: 2026-05-20 23:21:45.706072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3980fb83271c'
down_revision: Union[str, Sequence[str], None] = 'dfcc829741f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_participant_match_puuid', 'match_participants', ['match_id', 'puuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_participant_match_puuid', 'match_participants', type_='unique')
    # ### end Alembic commands ###
