"""add player_correct

Revision ID: 95b40df748db
Revises: cdcf4894f245
Create Date: 2026-05-20 21:43:07.601830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b40df748db'
down_revision: Union[str, Sequence[str], None] = 'cdcf4894f245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('game_name', sa.String(length=64), nullable=False),
    sa.Column('tag_line', sa.Text(), nullable=False),
    sa.Column('summoner_level', sa.Integer(), nullable=True),
    sa.Column('profile_icon_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('puuid')
    )
    op.create_index(op.f('ix_players_game_name'), 'players', ['game_name'], unique=False)
    op.create_index(op.f('ix_players_tag_line'), 'players', ['tag_line'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_tag_line'), table_name='players')
    op.drop_index(op.f('ix_players_game_name'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
