"""add matches, participants, ranked

Revision ID: d9a4fdfda983
Revises: 95b40df748db
Create Date: 2026-05-20 22:05:48.151005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9a4fdfda983'
down_revision: Union[str, Sequence[str], None] = '95b40df748db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('game_mode', sa.String(length=32), nullable=False),
    sa.Column('game_version', sa.String(length=16), nullable=False),
    sa.Column('game_duration', sa.Integer(), nullable=False),
    sa.Column('game_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_matches_queue_id'), 'matches', ['queue_id'], unique=False)
    op.create_table('match_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('champion_name', sa.String(length=64), nullable=False),
    sa.Column('team_position', sa.String(length=16), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('total_damage_dealt', sa.Integer(), nullable=False),
    sa.Column('gold_earned', sa.Integer(), nullable=False),
    sa.Column('cs', sa.Integer(), nullable=False),
    sa.Column('challenges_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['puuid'], ['players.puuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_participants_match_id'), 'match_participants', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_participants_puuid'), 'match_participants', ['puuid'], unique=False)
    op.create_table('ranked_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('queue_type', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=True),
    sa.Column('rank', sa.String(length=4), nullable=True),
    sa.Column('league_points', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('hot_streak', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['puuid'], ['players.puuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranked_entries_puuid'), 'ranked_entries', ['puuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ranked_entries_puuid'), table_name='ranked_entries')
    op.drop_table('ranked_entries')
    op.drop_index(op.f('ix_match_participants_puuid'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_match_id'), table_name='match_participants')
    op.drop_table('match_participants')
    op.drop_index(op.f('ix_matches_queue_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
